package breakout.animations;

import breakout.assets.PixelImage;

/*
 * Animations can alter the current frame generated by the view.
 * Finished Animations are being garbage-collected.
 */

public abstract class Animation {
	
	protected int width;
	protected int height;
	
	/* duration / total number of frames */
	protected int frames = 0;
	
	protected int currentFrame = 0;
	
	protected boolean finished = false;
	
	/* getters */
	public int numFrames() { return frames; }	
	public boolean hasFinished() { return finished; }
	
	/**
	 * alters the current frame based on the {currentFrame}
	 * @param frame (as rendered by the view)
	 * @return the altered frame
	 */
	public PixelImage renderFrame(PixelImage img) { return img; };
	
	public void nextFrame() {
		
		if(currentFrame > frames) {
			finished = true;
		}
		
		currentFrame++;		
	};

}
